### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/workplace#1]
- [x] Final Code Review
- [x] Add @ghunti as repo admin
- [x] Add @ghunti to github org
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Website PR: https://github.com/laravel-notification-channels/website/pull/13

**Comment by atymic** [comment]
@ghunti 

Everything should be set up now! 
You are good to tag the first release, and once done i'll merge the website PR :)

**Comment by ghunti** [comment]
@atymic Tagged 0.0.1 :-)
